server:
  port: 8000
spring:
  application:
    name: dbscanner-service
  datasource:
    url: jdbc:mysql://localhost:3306/zn_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
  jpa:
    ddl-auto: none
    show-sql: true
    dialect:
    format_sql: true
    use_sql_comments: true
ygg:
  annotation:
    comment:
      enable: false